export const questoes = {
    "Instabilidade de atenção": [
      "Desvia facilmente sua atenção do que está fazendo, quando recebe um pequeno estímulo.",
      "Tem dificuldade em prestar atenção à fala dos outros.",
      "Desorganização cotidiana.",
      "Frequentemente apresenta ”brancos” durante uma conversa.",
      "Tendência a interromper a fala do outro.",
      "Costuma cometer erros de fala, leitura ou escrita.",
      "Presença de hiperfoco.",
      "Dificuldade de permanecer em atividades obrigatórias de longa duração.",
      "Interrompe tarefas no meio.",
    ],
    "Hiperatividade fisica ou mental": [
      "Dificuldade em permanecer sentado por muito tempo.",
      "Está sempre mexendo com os pés ou as mãos.",
      "Constante sensação de inquietação ou ansiedade.",
      "Tendência a estar sempre ocupado com alguma problemática.",
      "Costuma fazer várias coisas ao mesmo tempo.",
      "Envolve-se em vários projetos ao mesmo tempo.",
      "Às vezes se envolve em situações de alto risco.",
      "Frequentemente fala sem parar.",
    ],
    "Impulsividade": [
      "Baixa tolerância à frustração.",
      "Costuma responder a alguém antes que este complete a pergunta.",
      "Costuma provocar situações constrangedoras.",
      "Impaciência marcante no ato de esperar ou aguardar por algo.",
      "Impulsividade para comprar, sair de empregos, romper relacionamentos.",
      "Reage irrefletidamente às provocações, críticas ou rejeição.",
      "Tendência a não seguir regras ou normas preestabelecidas.",
      "Compulsividade.",
      "Sexualidade instável.",
      "Ações contraditórias.",
      "Hipersensibilidade.",
      "Hiper-reatividade.",
      "Tendência a culpar os outros.",
      "Mudanças bruscas e repentinas de humor.",
      "Tendência a ser muito criativo e intuitivo.",
      "Tendência ao ”desespero”.",
    ],
    "Sintomas secundários": [
      "Tendência a ter um desempenho profissional abaixo do esperado.",
      "Baixa auto-estima.",
      "Dependência química.",
      "Depressões frequentes.",
      "Intensa dificuldade em manter relacionamentos afetivos.",
      "Demora excessiva para iniciar ou executar algum trabalho.",
      "Baixa tolerância ao estresse.",
      "Tendência a apresentar um lado ”criança”.",
      "Tendência a tropeçar, cair ou esbarrar em objetos.",
    ],
  };
  